### ISSUE TITLE
Error on self toctree

### ISSUE THREAD

**Issue by Fazatholomew** [TDKorn/sphinx-readme#8]
I was getting this error:
``` bash
Traceback (most recent call last):
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx_readme/__init__.py", line 51, in resolve
    parser.resolve()
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx_readme/parser.py", line 289, in resolve
    rst = self.replace_toctrees(src, rst)
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx_readme/parser.py", line 383, in replace_toctrees
    link, subs = format_hyperlink(target, text=entry['title'])
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx_readme/utils/rst.py", line 36, in format_hyperlink
    if "`" in text:
TypeError: argument of type 'NoneType' is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx/application.py", line 355, in build
    self.events.emit('build-finished', None)
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function resolve at 0x1062e0550> for event 'build-finished' threw an exception (exception: argument of type 'NoneType' is not iterable)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx_readme/__init__.py", line 51, in resolve
    parser.resolve()
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx_readme/parser.py", line 289, in resolve
    rst = self.replace_toctrees(src, rst)
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx_readme/parser.py", line 383, in replace_toctrees
    link, subs = format_hyperlink(target, text=entry['title'])
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx_readme/utils/rst.py", line 36, in format_hyperlink
    if "`" in text:
TypeError: argument of type 'NoneType' is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx/application.py", line 361, in build
    self.events.emit('build-finished', err)
  File "/Users/jimboy/Documents/CS/send-the-raven/.venv/lib/python3.10/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function resolve at 0x1062e0550> for event 'build-finished' threw an exception (exception: argument of type 'NoneType' is not iterable)
```

When I am trying to put my index.rst on toctree using ``self``:
```rst
Documentation
============

.. toctree::
   :maxdepth: 2
   :hidden:
   
   Get Started <self>
   example
   api
   contribute
```

**Comment by TDKorn** [comment]
Hi! This should be fixed in `v0.2.4`, please try updating the package and let me know if you have any issues still.
